### ISSUE TITLE
Version rules fail in case of any digit 

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/spectral-url-versioning#1]
As a user i should be able to add digits and numbers to the URLs without getting versioning errors. 

i.e. 

```
  "servers": [
    {
      "url": "http://localhost:300"
    }
  ],
```

```
  "paths": {
    "/users/1231/{userId}":
```

These shouldn't fail

**Comment by philsturgeon** [comment]
Good fuzz testing! Currently this is intentional, as off the top of my head I cannot think of a use-case where a number is in a URL like this and its not a version.

Do we want to restrict it to just numbers prefixed with `v`?

**Comment by mnaumanali94** [comment]
The port within the URL is an example? I would say we restrict it to prefixed v or version.

**Comment by philsturgeon** [comment]
Fixed the port number issue in https://github.com/stoplightio/spectral-url-versioning/commit/a2fb44037e98dc394fe0f2cb3b01c9ed701a8c3a
